version: '3.9'

services:
  nest_app:
    container_name: nest_app
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development # production / development
    command: pnpm start:dev # Dev only
    env_file:
      - .env.development
      # - .env.production
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app # Dev only
  db:
    container_name: nest_mysql
    image: mysql:8.2.0
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: er-vinhntt
      MYSQL_DATABASE: nest_topic
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt

volumes:
  db_data:
